import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Sparkles, BookOpen, Users, TrendingUp, Star, ArrowRight, Quote, PenTool } from 'lucide-react';
import { Card, Badge, Avatar, Skeleton, Button } from '../components/ui';
import api from '../services/api';

const fadeUp = { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6 } };

export default function HomePage() {
  const [trending, setTrending] = useState([]);
  const [featured, setFeatured] = useState([]);
  const [books, setBooks] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      api.get('/poetry/trending').then((r) => setTrending(r.data.data)).catch(() => {}),
      api.get('/poetry/featured').then((r) => setFeatured(r.data.data)).catch(() => {}),
      api.get('/books/featured').then((r) => setBooks(r.data.data)).catch(() => {}),
      api.get('/stats').then((r) => setStats(r.data.data)).catch(() => {}),
    ]).finally(() => setLoading(false));
  }, []);

  return (
    <div>
      {/* Hero */}
      <section className="relative min-h-[90vh] flex items-center overflow-hidden">
        <div className="absolute inset-0 gradient-bg opacity-10" />
        <div className="absolute inset-0">
          {[...Array(20)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute w-1 h-1 rounded-full bg-[var(--color-primary)]"
              style={{ left: `${Math.random() * 100}%`, top: `${Math.random() * 100}%` }}
              animate={{ opacity: [0.2, 0.8, 0.2], scale: [1, 1.5, 1] }}
              transition={{ duration: 3 + Math.random() * 2, repeat: Infinity, delay: Math.random() * 2 }}
            />
          ))}
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <motion.div {...fadeUp} className="max-w-3xl">
            <Badge variant="gold">AI-Powered Literary Universe</Badge>
            <h1 className="text-5xl sm:text-7xl font-bold mt-6 leading-tight">
              Where <span className="gradient-text font-serif italic">Poetry</span> Meets{' '}
              <span className="gradient-text">Intelligence</span>
            </h1>
            <p className="text-lg mt-6 max-w-xl" style={{ color: 'var(--text-muted)' }}>
              Create shayari, ghazals, and poems with AI. Discover literary masterpieces. Build your poetry empire on the world's most advanced literary platform.
            </p>
            <div className="flex flex-wrap gap-4 mt-8">
              <Link to="/ai-studio" className="btn-primary flex items-center gap-2">
                <Sparkles size={18} /> Start Creating
              </Link>
              <Link to="/explore" className="btn-secondary flex items-center gap-2">
                Explore Poetry <ArrowRight size={18} />
              </Link>
            </div>
          </motion.div>

          {stats && (
            <motion.div {...fadeUp} transition={{ delay: 0.3 }} className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-16">
              {[
                { label: 'Poems', value: stats.totalPoetry, icon: PenTool },
                { label: 'Books', value: stats.totalBooks, icon: BookOpen },
                { label: 'Writers', value: stats.totalUsers, icon: Users },
                { label: 'Orders', value: stats.totalOrders, icon: TrendingUp },
              ].map(({ label, value, icon: Icon }) => (
                <Card key={label} className="text-center !p-4">
                  <Icon size={24} className="mx-auto mb-2 text-[var(--color-primary)]" />
                  <p className="text-2xl font-bold">{value?.toLocaleString() || '0'}</p>
                  <p className="text-sm" style={{ color: 'var(--text-muted)' }}>{label}</p>
                </Card>
              ))}
            </motion.div>
          )}
        </div>
      </section>

      {/* AI Demo */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold">AI Poetry Demo</h2>
          <p style={{ color: 'var(--text-muted)' }} className="mt-2">Experience the magic of AI-generated literature</p>
        </div>
        <Card className="max-w-2xl mx-auto !p-8 text-center">
          <Quote size={32} className="mx-auto mb-4 text-[var(--color-primary)] opacity-50" />
          <p className="text-xl font-serif italic leading-relaxed poetry-text">
            Mohabbat ek aisi darya hai
            <br />Jisme doob kar hi samajh aati hai uski gehraai
          </p>
          <p className="mt-4 text-sm" style={{ color: 'var(--text-muted)' }}>Generated by KavyaKosh AI · Romantic Shayari · Hindi</p>
          <Link to="/ai-studio" className="btn-primary inline-flex items-center gap-2 mt-6">
            <Sparkles size={16} /> Try AI Studio
          </Link>
        </Card>
      </section>

      {/* Trending Shayari */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h2 className="text-3xl font-bold flex items-center gap-2"><TrendingUp className="text-[var(--color-primary)]" /> Trending Shayari</h2>
          </div>
          <Link to="/explore?type=shayari" className="text-[var(--color-primary)] text-sm flex items-center gap-1 hover:underline">
            View All <ArrowRight size={16} />
          </Link>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {loading ? [...Array(3)].map((_, i) => <Skeleton key={i} className="h-48" />) :
            trending.slice(0, 6).map((item, i) => (
              <motion.div key={item._id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}>
                <Link to={`/poetry/${item._id}`}>
                  <Card hover className="h-full">
                    <div className="flex items-center gap-3 mb-4">
                      <Avatar src={item.author?.avatar} name={item.author?.name} />
                      <div>
                        <p className="font-medium text-sm">{item.author?.name}</p>
                        <Badge>{item.type}</Badge>
                      </div>
                    </div>
                    <h3 className="font-semibold mb-2">{item.title}</h3>
                    <p className="text-sm poetry-text line-clamp-3">{item.content}</p>
                    <div className="flex items-center gap-4 mt-4 text-xs" style={{ color: 'var(--text-muted)' }}>
                      <span>{item.views} views</span>
                      <span>{item.likes?.length || 0} likes</span>
                    </div>
                  </Card>
                </Link>
              </motion.div>
            ))}
        </div>
      </section>

      {/* Featured Books */}
      <section style={{ background: 'var(--bg-secondary)' }} className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-3xl font-bold flex items-center gap-2"><BookOpen className="text-[var(--color-primary)]" /> Featured Books</h2>
            <Link to="/marketplace" className="text-[var(--color-primary)] text-sm flex items-center gap-1 hover:underline">
              Browse Store <ArrowRight size={16} />
            </Link>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {loading ? [...Array(4)].map((_, i) => <Skeleton key={i} className="h-72" />) :
              books.map((book, i) => (
                <motion.div key={book._id} initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: i * 0.1 }}>
                  <Link to={`/marketplace/${book._id}`}>
                    <Card hover className="!p-0 overflow-hidden">
                      <img src={book.coverImage} alt={book.title} className="w-full h-48 object-cover" />
                      <div className="p-4">
                        <h3 className="font-semibold text-sm line-clamp-1">{book.title}</h3>
                        <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>{book.author?.name}</p>
                        <div className="flex items-center gap-2 mt-2">
                          <Star size={14} className="text-[var(--color-gold)] fill-[var(--color-gold)]" />
                          <span className="text-sm">{book.rating}</span>
                          <span className="text-sm font-bold ml-auto text-[var(--color-primary)]">
                            ₹{book.discountPrice || book.price}
                          </span>
                        </div>
                      </div>
                    </Card>
                  </Link>
                </motion.div>
              ))}
          </div>
        </div>
      </section>

      {/* Premium CTA */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <Card className="text-center !p-12 relative overflow-hidden">
          <div className="absolute inset-0 gradient-bg opacity-5" />
          <div className="relative">
            <h2 className="text-3xl font-bold mb-4">Unlock Your Creative Potential</h2>
            <p className="max-w-lg mx-auto mb-8" style={{ color: 'var(--text-muted)' }}>
              Get unlimited AI generations, premium templates, advanced analytics, and priority support.
            </p>
            <Link to="/pricing" className="btn-primary">View Premium Plans</Link>
          </div>
        </Card>
      </section>
    </div>
  );
}
